[package]
name = "hms-mqtt-publish"
version = "0.2.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
env_logger = "0.10.1"
hms2mqtt = { path = "hms2mqtt" }
log = "0.4.20"
rumqttc = "0.23.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.193"
toml = "0.8.8"
