[package]
name = "pbf-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.7", features = ["derive"] }
crc16 = "0.4.0"
env_logger = "0.10.0"
log = "0.4.20"
protobuf = "3.3.0"
protobuf-json = "0.3.0"
rumqttc = "0.23.0"

[build-dependencies]
protobuf-codegen = "3.3.0"
