[package]
name = "hms-mqtt-publish"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
crc16 = "0.4.0"
env_logger = "0.10.1"
log = "0.4.20"
protobuf = "3.3.0"
rumqttc = "0.23.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hostname = "0.3.1"
toml = "0.8.8"
serde_derive = "1.0.193"

[build-dependencies]
protobuf-codegen = "3.3.0"
