---
name: Hoymiles HMS Wifi Addon (Nightly)
version: 'v0.3'
slug: ha-hoymiles-wifi-addon-nightly
description: Publishes telemetry information from Hoymiles HMS-XXXXW-T2 micro-inverters to your home assistant MQTT broker
url: https://github.com/dominikandreas/hms-mqtt-publisher/tree/feature/ha_addon_nightly/ha-hoymiles-wifi-addon-nightly
init: false
arch:                              # List of supported architectures.
  - armv7
  - aarch64
  - amd64
startup: application              # When the add-on should start.
boot: auto                        # Boot options, auto or manual.
services: ['mqtt:want']
options:                          # Default options value for the add-on.
  inverter_host: ''
  mqtt_broker_host: ''
  mqtt_username: ''
  mqtt_password: ''
  mqtt_port: 1883
  debug_logging: false
schema:                            # Schema validation for the options.
  inverter_host: str
  mqtt_broker_host: str?
  mqtt_username: str?
  mqtt_password: str?
  mqtt_port: int
  debug_logging: bool