name: Hoymiles HMS Wifi Addon
version: '0.1'
slug: ha-hoymiles-wifi-addon
description: Publishes telemetry information from Hoymiles HMS-XXXXW-T2 micro-inverters to your home assistant MQTT broker
init: false
arch:                              # List of supported architectures.
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application              # When the add-on should start.
boot: auto                        # Boot options, auto or manual.
options:                          # Default options value for the add-on.
  inverter_host: ''
  mqtt_broker_host: ''
  mqtt_username: ''
  mqtt_password: ''
  mqtt_port: 1883
schema:                            # Schema validation for the options.
  inverter_host: str
  mqtt_broker_host: str
  mqtt_username: str
  mqtt_password: str
  mqtt_port: int
environment:                       # Environment variables for the add-on.
  INVERTER_HOST: 'options.inverter_host'
  MQTT_BROKER_HOST: 'options.mqtt_broker_host'
  MQTT_USERNAME: 'options.mqtt_username'
  MQTT_PASSWORD: 'options.mqtt_password'
  MQTT_PORT: 'options.mqtt_port'